### ISSUE TITLE
python3.6下不可以用

### ISSUE THREAD

**Issue by YouRanLongYing** [xlzd/img2html#11]
D:\Workspace>img2html -i baby.jpg -o out.html
Traceback (most recent call last):
  File "D:\Software\Python3_6\Scripts\img2html-script.py", line 11, in <module>
    load_entry_point('img2html==0.0.7', 'console_scripts', 'img2html')()
  File "d:\software\python3_6\lib\site-packages\img2html\__init__.py", line 35, in main
    font_family=args.font,
  File "d:\software\python3_6\lib\site-packages\img2html\converter.py", line 73, in __init__
    char = char.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by morinstar** [comment]
遇到了同样的问题，还在纠结是不是应该改成encode

**Comment by morinstar** [comment]
更新一下，把72-73行删掉以后再把next()、xrange()问题解决，是可以在3.6环境下运行了，但是得到的图片是由无法识别的符号（黑底?）组成，我也不知道应该怎么搞了，来个大神指导下啊xox

**Comment by morinstar** [comment]
实在搞不懂字符串的格式和cycle()能接受的类型，如上更改以后是可以识别英文字符串了，但是中文的还是不行

**Comment by lao-zhang** [comment]
请教一下，生成的html 在哪个文件夹呢

**Comment by liguobao** [comment]
@lao-zhang  -i 输出路径

**Comment by liguobao** [comment]
python2.7正常运行...
@morinstar

**Comment by Xieliang0724** [comment]
输出 路径在哪啊？找不到么
