### ISSUE TITLE
characters 参数中文参数报错

### ISSUE THREAD

**Issue by liguobao** [xlzd/img2html#4]
progress: 100.00%root@DESKTOP-G3JIH3M:/mnt/c/Users/liguobao# img2html -c '伊' -s 10 -i ./yibaobao.jpg -o yibaobao.html
progress: 100.00%Traceback (most recent call last):
  File "/usr/local/bin/img2html", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/img2html/__init__.py", line 37, in main
    html = converter.convert(getattr(args, 'in'))
  File "/usr/local/lib/python2.7/dist-packages/img2html/converter.py", line 89, in convert
    return self.render(html_image)
  File "/usr/local/lib/python2.7/dist-packages/img2html/converter.py", line 99, in render
    width=self.font_size * len(html_image[0]) * 2
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 20, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)

**Comment by xlzd** [comment]
fixed @liguobao
